allowBuilds:
  msw: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

overrides:
  react: "19.2.3"
  react-dom: "19.2.3"
  "@types/react": "^19"
  "@types/react-dom": "^19"
