packages:
  - '.'

allowBuilds:
  msw: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

overrides:
  react: "19.2.3"
  react-dom: "19.2.3"
  "@types/react": "^19"
  "@types/react-dom": "^19"
