name: Deploy frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy frontend service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e
            cd /home/purushotam/atlas/atlas_frontend
            git pull origin main

            cd /home/purushotam/atlas
            docker compose up -d --build atlas-frontend


